# Are you providing the output of a combined featurecounts or kallisto output?
# If providing kallisto then set to True and provide path to the kallisto quant dir
kallisto: True
kallisto_dir: "kallisto_input/L363/quant"

# Specify if macaque, mouse or human
species: "human"
