# Are you providing the output of a combined featurecounts or kallisto output?
# If providing kallisto then set to True and provide path to the kallisto quant dir
# if not using kallisto, set to False, place gene counts as genes.tsv file in the main directory and the featurecounts design file as a design_<test>_<control>_<stat>_<designColname>_<reportTitle>_featurecounts.tsv
kallisto: True
kallisto_dir: "kallisto_input/AMO1/quant"

# Specify if macaque, mouse or human
species: "human"
