---
title: "Differential expression analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Source R functions, message=FALSE, warning=FALSE, include=FALSE}

source("R_functions/utils.R", local = knitr::knit_global())
source("R_functions/read_data.R", local = knitr::knit_global())

```


# Top gene hits

```{r Top genes, echo=FALSE, fig.height=10, fig.width=10, message=FALSE, warning=FALSE, paged.print=TRUE}

Annotate_genes_results(res = DeSeq2_return$res,
                       title = Plot_title,
                       control = Control,
                       test = Test,
                       stats = deseq2_stats_test
)


```


# Dispersion Plot

```{r Dispersion Plot, echo=FALSE, fig.height=8, fig.width=8, message=FALSE, warning=FALSE, paged.print=TRUE}

Dispersion_Plot(de_seq = DeSeq2_return$de_seq,
                title = Plot_title,
                ymin = 10^-9
                
  
)



```

#MA Plots


```{r MA PLots, echo=FALSE, fig.height=8, fig.width=8, message=FALSE, warning=FALSE, paged.print=TRUE}

MA_Plot(de_seq = DeSeq2_return$de_seq,
        res = DeSeq2_return$res,
        test = Test,
        title = Plot_title
        
        
  
) 

```


# Volcano Plot

```{r Volcano Plots, echo=FALSE, fig.height=9, fig.width=9, message=FALSE, warning=FALSE, paged.print=TRUE}

##log2 fold change cut off for Volcano plot.
FC_VP <- 1

##pvalue cut off for Volcano plot.
pvalue_VP <- 1e-8

Volcano <- 
  Volcano_Plots(de_seq = DeSeq2_return$de_seq, 
              test = Test, 
              res = DeSeq2_return$res, 
              labels = TRUE,
              title = Plot_title,
              pval = pvalue_VP, 
              label_list = NULL,
              FC = FC_VP)

Volcano
#ggsave(paste0(plots_dir, Volcano$labels$title, "_", Volcano$labels$subtitle,"NFKB_Volcano_Plots.png"))
label_list <- str_subset(negate=T,pattern="ZNF", c(UpSigTFs, DownSigTFs, "ABCB1", "XBP1", "ERN1", "PSMB5"))
Volcano <- Volcano_Plots(de_seq = DeSeq2_return$de_seq, 
              test = Test, 
              res = DeSeq2_return$res, 
              labels = TRUE,
              title = Plot_title,
              #pval = pvalue_VP, 
              pval=0.05,
              label_list = label_list,
              #filter_specific = c(UpSigGenes, DownSigGenes),
              FC = 1)
Volcano
ggsave(paste0(plots_dir, Volcano$labels$title, "_", Volcano$labels$subtitle,"shared_TFs_PIres.png"))
UpSigGenes
DownSigGenes
DownSigTFs
results_annotated %>%
  filter(hgnc_symbol=="ABCB1")
label_list
write.table(row.names = FALSE, c(UpSigTFs, DownSigTFs), "results/common_plots/shared_TFs.txt", col.names = FALSE, quote=F)
```


