---
title: "Untitled"
output: html_document
date: "2023-05-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## RUN this script after running enrichment.rmd and GRN.rmd
```


```{r common_tfs}
#CeTF
RIF_common_TFs <- RIF_table$TF

#RCis
Rcis_up_TFs <- motifEnrichmentTable_wGenes[motifEnrichmentTable_wGenes[ , geneSet == "CarUp"]] %>% dplyr::pull(TF_highConf) %>% str_replace_all(" \\s*\\([^\\)]+\\). ", "") %>%
  str_split("; ") %>% unlist() %>% unique()
Rcis_down_TFs <- motifEnrichmentTable_wGenes[motifEnrichmentTable_wGenes[ , geneSet == "CarDown"]] %>% dplyr::pull(TF_highConf) %>% str_replace_all(" \\s*\\([^\\)]+\\). ", "") %>%
  str_split("; ") %>% unlist() %>% unique()
Rcis_common_TFs <- RcisTarget_TFs

#TFEA CHIP
TFEA_CHIP_identified_TFs <-unique(c(TFEA_Chip_GSEA_enriched_TFs, TFEA_Chip_ranked_TFs))

## chea3
chea3_top_hits$TF

##decounpleR
decoupleR_deg_top50_variable_TFs
decoupleR_mat_top50_variable_TFs


make_heatmap(specific_tfs = decoupleR_mat_top50_variable_TFs, pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "decoupleR_mat_top50_variable_TFs.png"), height = 8, width = 8)
make_heatmap(specific_tfs = decoupleR_deg_top50_variable_TFs, pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "decoupleR_deg_top50_variable_TFs.png"), height = 8, width = 8)
make_heatmap(specific_tfs = intersect(decoupleR_mat_top50_variable_TFs,decoupleR_deg_top50_variable_TFs), pathways = NULL)
make_heatmap(specific_tfs = chea3_top_hits$TF[1:40], pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "_Chea3_TFs.png"), height = 7, width=8)
make_heatmap(specific_tfs = Rcis_common_TFs, pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "_RCis_TFs.png"), height = 7, width=8)

### All top TFs
All_top_TFs <- c(RIF_common_TFs, Rcis_common_TFs, TFEA_CHIP_identified_TFs, chea3_top_hits$TF[1:100], decoupleR_deg_top50_variable_TFs, decoupleR_mat_top50_variable_TFs) %>% unique()
write.table(All_top_TFs, row.names = FALSE, quote = FALSE, col.names = FALSE, file = paste0(results_dir, "All_top_TFs.txt"))


```



```{r common_grn_hubs}
##bionero
bionero_grn_hubs
make_heatmap(specific_tfs = bionero_grn_hubs$Gene[1:50], pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "_GRN_enriched_hub_genes.png"), height = 8, width = 8)
bioNERO_gcn_hubs$Module %>% unique()
bioNERO_gcn_hubs
make_heatmap(specific_tfs = bioNERO_gcn_hubs %>% filter(Module == "magenta") %>% pull(Gene) %>% head(75), pathways = NULL)
make_heatmap(specific_tfs = bioNERO_gcn_hubs %>% filter(Module == "brown") %>% pull(Gene) %>% head(75), pathways = NULL)
ggsave(paste0(plots_dir, Plot_title,"_bionero__gcn_enriched_hub_genes.png"), height = 10, width=8)

#bioNERO_gcn_hubs

#GWENA
GWENA_gcn_hub_genes <- c()
for (i in 1:length(GWENA_sig_modules)) {
  GWENA_gcn_hub_genes <- c(GWENA_gcn_hub_genes, names(GWENA_hub_genes[[i]]))
  make_heatmap(specific_tfs = names(GWENA_hub_genes[[i]]), pathways = NULL)
  a <- paste0("_GWENA_ME", i, ".png")
  ggsave(paste0(plots_dir, Plot_title, a), height = 6, width=8)

}
make_heatmap(specific_tfs = GWENA_gcn_hub_genes, pathways = NULL)
ggsave(paste0(plots_dir, Plot_title,"_GWENA_modules_all.png"), height = 8, width=8)

## WGCNA
ME3 <- gene_module_key %>% filter(module == "ME3") %>% pull(gene)
make_heatmap(specific_tfs = ME3, pathways = NULL)
ggsave(paste0(plots_dir, Plot_title,"_WGCNA_module_ME3.png"), height = 20)

# ME4 <- gene_module_key %>% filter(module == "ME4") %>% pull(gene)
# make_heatmap(specific_tfs = ME4, pathways = NULL)
# ggsave(paste0(plots_dir, Plot_title,"_WGCNA_module_ME4.png"), height = 12)
# ME16 <- gene_module_key %>% filter(module == "ME16") %>% pull(gene)
# make_heatmap(specific_tfs = ME16, pathways = NULL)
# ggsave(paste0(plots_dir, Plot_title,"_WGCNA_module_ME16.png"), height = 12)
# ME9 <- gene_module_key %>% filter(module == "ME9") %>% pull(gene)
# make_heatmap(specific_tfs = ME9, pathways = NULL)
# ggsave(paste0(plots_dir, Plot_title,"_WGCNA_module_ME9.png"), height = 16)

## CEMItool
cemitools_results_4000 <- cemitool_results
make_heatmap(specific_tfs = CEMiTool::get_hubs(cemitools_results_4000, 50)[[1]] %>% names(), pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "CEMiTool_m1.png"), height = 6,width=8)
make_heatmap(specific_tfs = CEMiTool::get_hubs(cemitools_results_4000, 50)[[2]] %>% names(), pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "CEMiTool_m2.png"), height = 6,width=8)
make_heatmap(specific_tfs = CEMiTool::get_hubs(cemitools_results_4000, 50)[[3]] %>% names(), pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "CEMiTool_m3.png"), height = 6, width = 10)
make_heatmap(specific_tfs = CEMiTool::get_hubs(cemitools_results_4000, 50)[[4]] %>% names(), pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "CEMiTool_m4.png"), height = 6, width=8)

## REGENRCIH

make_heatmap(specific_tfs = Regenrich_results_COEN_results$reg[1:50], pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "RegEnrich_COEN.png"), height = 6, width = 8)

make_heatmap(specific_tfs = Regenrich_results_GRN_results$reg[1:50], pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "RegEnrich_GRN.png"), height = 6, width = 8)

make_heatmap(specific_tfs = c(Regenrich_results_COEN_results$reg[1:50], Regenrich_results_GRN_results$reg[1:50]) %>% unique(), pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "RegEnrich_All.png"), height = 12, width = 8)


cemitools_gcn_hub_genes <- c()
for (i in 1:length(CEMiTool_sig_modules)) {
  cemitools_gcn_hub_genes <- c(cemitools_gcn_hub_genes, names(CEMiTool_hub_genes[[i]]))
}
make_heatmap(specific_tfs = cemitools_gcn_hub_genes, pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "CEMiTool_all.png"), height = 9, width=8)
```


```{r all_hubs}
## All top hubs

All_top_hubs <- c(bionero_grn_hubs$Gene, cemitools_gcn_hub_genes, Regenrich_results_COEN_results$reg[1:50], Regenrich_results_GRN_results$reg[1:50]) %>% unique()
write.table(All_top_hubs, row.names = FALSE, quote = FALSE, col.names = FALSE, file = paste0(results_dir, "All_top_hubs.txt"))


intersecting_hubs <- intersect(All_top_hubs, All_top_TFs)
write.table(intersecting_hubs, row.names = FALSE, quote = FALSE, col.names = FALSE, file = paste0(results_dir, Plot_title, "_", Test, "_intersecting_hubs.txt"))
make_heatmap(specific_tfs = intersecting_hubs, pathways = NULL)
ggsave(paste0(plots_dir, Plot_title, "_", Test, "_intersecting_hub_TF_genes.png"), height = 7, width = 8)
```

